name: Train Chatbot Model with Large Dataset

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow numpy pandas

      # Prepare data and train the model
      - name: Train the model with large data
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          python train_model.py

      - name: Track large model files with Git LFS
        run: |
          git lfs track "chat_model_large.h5"
          git lfs track "chat_model_large.tflite"
          git add .gitattributes

      # Commit and push the trained model to the repository
      - name: Commit and push the trained model
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add chat_model_large.h5 chat_model_large.tflite tokenizer.pkl
          git commit -m "Trained model and TFLite conversion for large dataset"
          git push
