name: Test Chatbot TFLite Model

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  test-model:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install required packages
        run: |
          python -m pip install --upgrade pip
          pip install numpy tflite-runtime tensorflow keras pandas

      # Run the Python test script
      - name: Run the chatbot test with input "hi"
        run: |
          python test.py
